friends/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('profiles.urls')),
    path('auth/', include('django.contrib.auth.urls')),

    path('', include('threads.urls'))
]

profiles/urls.py
from django.urls import path
from .views import LoginView, RegisterView, profile, accept_friend_request, send_friend_request

app_name = 'profiles'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<user_id>', profile, name='profile'),
    path('send_friend_request/<user_id>', send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<request_id>', accept_friend_request, name='accept_friend_request'),
]

threads/urls.py
from django.urls import path

from . import views

app_name = 'threads'
urlpatterns = [
    path('', view = views.index, name='index'),
    path('t/new/', view = views.new, name='new'),
    path('t/<thread_id>/', view = views.detail, name='detail'),
    path('t/<thread_id>/upvote/', view = views.upvote, name='upvote'),
    path('t/<thread_id>/comment/', view = views.comment, name='comment'),
]

threads/models.py
from django.db import models
from django.utils import timezone

from profiles.models import User

class Thread(models.Model):
    title = models.CharField(max_length=256)
    text = models.CharField(max_length=512)
    pub_date = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title

class Comment(models.Model):
    text = models.CharField(max_length=256)
    pub_date = models.DateTimeField(default=timezone.now)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.text

class Upvote(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vote_date = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.user.username + ' upvoted "' + self.thread.title + '"'

threads/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Thread, Comment, Upvote

def index(request):
    recent_threads = Thread.objects.order_by('-pub_date')[:5]
    popular_threads = Thread.objects.annotate(upvotes=Count('upvote')).order_by('-upvotes')[:5]
    return render(request, 'threads/index.html', { 'recent_threads': recent_threads, 'popular_threads': popular_threads })

def detail(request, thread_id):
    thread = get_object_or_404(Thread, id=thread_id)
    comments = Comment.objects.filter(thread=thread.id).order_by('-pub_date')
    upvoted = request.user.is_authenticated and Upvote.objects.filter(thread=thread, user=request.user).count() != 0
    return render(request, 'threads/detail.html', { 'thread': thread, 'comments': comments, 'upvoted': upvoted })

@login_required
def new(request):
    if request.method == 'POST':
        new_thread = Thread(title=request.POST['thread-title'], text=request.POST['thread-text'], creator=request.user)
        new_thread.save()
        return HttpResponseRedirect(reverse('threads:detail', args=(new_thread.id, )))
    return render(request, 'threads/new.html')

@login_required
def upvote(request, thread_id):
    thread = get_object_or_404(Thread, id=thread_id)
    upvoted = Upvote.objects.filter(thread=thread, user=request.user).count() != 0
    if not upvoted:
        Upvote.objects.create(thread=thread, user=request.user)
    return HttpResponseRedirect(reverse('threads:detail', args=(thread.id, )))

@login_required
def comment(request, thread_id):
    thread = get_object_or_404(Thread, id=thread_id)
    new_comment = Comment(text=request.POST['comment-text'], thread=thread, creator=request.user)
    new_comment.save()
    return HttpResponseRedirect(reverse('threads:detail', args=(thread.id, )))

templates/threads/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends Network</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Friends Network</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="/t/new">New Thread</a>
                    <a href="{% url 'profiles:profile' user.id %}" class="nav-link">My Profile</a>
                    <a href="{% url 'logout' %}" class="nav-link">Log out</a>
                    {% else %}
                    <a href="{% url 'login' %}" class="nav-link">Log in</a>
                    <a href="{% url 'profiles:register' %}" class="nav-link">Sign up</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>

</html>

templates/threads/detail.html
{% extends 'threads/base.html' %}

{% block content %}
    <div class="container my-3">
        <div class="mb-5">
            <h2>{{ thread.title }}</h2>
            <p>by <a class="text-decoration-none" href="{% url 'profiles:profile' thread.creator.id %}">{{ thread.creator.username }}</a> in {{ thread.pub_date }}</p>
            <p>{{ thread.text }}</p>
            <div class="d-flex align-items-center">
                {% if upvoted %}
                    {% with upvotes=thread.upvote_set.count|add:"-1" %}
                        {% if upvotes == 0 %}
                            <p>You gave an upboat!</p>
                        {% else %}
                            <p>You and {{ upvotes }} other {{ upvotes|pluralize:"person,people" }} have upboated!</p>
                        {% endif %}
                    {% endwith %}
                {% else %}
                    {% if user.is_authenticated %}
                        <form action="{% url 'threads:upvote' thread.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary btn-sm me-3">Give an upboat</button>
                        </form>
                    {% endif %}
                    {% with upvotes=thread.upvote_set.count %}
                        <span>{{ upvotes }} {{ upvotes|pluralize:"person,people" }} have upboated!</span>
                    {% endwith %}
                {% endif %}
            </div>
        </div>

        {% if user.is_authenticated %}
        <div class="mb-5">
            <form action="{% url 'threads:comment' thread.id %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <textarea class="form-control" name="comment-text" id="comment-text" rows="3" placeholder="Make a comment..."></textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Submit</button>
            </form>
        </div>
        {% endif %}

    <h3>Comments</h3>
    {% if comments.count > 0 %}
        <ul class="list-group">
            {% for comment in comments %}
                <li class="list-group-item">
                    <p>{{ comment.text }}</p>
                    <span>by <a class="text-decoration-none" href="{% url 'profiles:profile' comment.creator.id %}">{{ comment.creator.username }}</a> in {{ comment.pub_date }}</span>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No comments were made on this thread.</p>
    {% endif %}
</div>
{% endblock %}

templates/threads/index.html
{% extends 'threads/base.html' %}

{% block content %}

<div class="container my-3">
    <h2>Recent Threads</h2>
    <div class="list-group list-group-flush">
        {% for thread in recent_threads %}
        <li class="list-group-item">
            <a class="text-decoration-none text-reset" href="{% url 'threads:detail' thread.id %}">
                <div class="d-flex justify-content-between align-items-center">
                    <h5 class="mb-1">{{ thread.title }}</h5>
                    <div class="d-flex">
                        <span class="badge bg-primary rounded-pill mx-3">{{ thread.upvote_set.count }} upboat{{ thread.upvote_set.count|pluralize }}</span>
                        <span class="badge bg-primary rounded-pill">{{ thread.comment_set.count }} comment{{ thread.comment_set.count|pluralize }}</span>
                    </div>
                </div>
                <p class="mb-1 text-truncate">{{ thread.text }}</p>
                <small>by <a class="text-decoration-none" href="{% url 'profiles:profile' thread.creator.id %}">{{ thread.creator.username }}</a> in {{ thread.pub_date }}</small>
            </a>
        </li>
        {% endfor %}
    </div>
</div>

<div class="container my-3">
    <h2>Popular Threads</h2>
    <div class="list-group list-group-flush">
        {% for thread in popular_threads %}
        <li class="list-group-item">
            <a class="text-decoration-none text-reset" href="{% url 'threads:detail' thread.id %}">
                <div class="d-flex justify-content-between align-items-center">
                    <h5 class="mb-1">{{ thread.title }}</h5>
                    <div class="d-flex">
                        <span class="badge bg-primary rounded-pill mx-3">{{ thread.upvote_set.count }} upboat{{ thread.upvote_set.count|pluralize }}</span>
                        <span class="badge bg-primary rounded-pill">{{ thread.comment_set.count }} comment{{ thread.comment_set.count|pluralize }}</span>
                    </div>
                </div>
                <p class="mb-1 text-truncate">{{ thread.text }}</p>
                <small>by <a class="text-decoration-none" href="{% url 'profiles:profile' thread.creator.id %}">{{ thread.creator.username }}</a> in {{ thread.pub_date }}</small>
            </a>
        </li>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/threads/new.html
{% extends 'threads/base.html' %}

{% block content %}
<div class="container my-3">

    <h2>New Thread</h2>
    <form action="{% url 'threads:new' %}" method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label for="thread-title" class="form-label">Title</label>
            <input type="text" class="form-control" id="thread-title" name="thread-title" placeholder="An interesting title..." required>
        </div>
        <div class="mb-3">
            <label for="thread-text" class="form-label">Text <small class="text-muted">(optional)</small></label>
            <textarea class="form-control" id="thread-text" name="thread-text" rows="3"></textarea>
        </div>
        <input type="submit" value="Submit" class="btn btn-primary btn-sm">
    </form>
</div>
{% endblock %}