friends/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('profiles.urls')),
    path('auth/', include('django.contrib.auth.urls')),

    path('', include('threads.urls'))
]

profiles/urls.py
from django.urls import path
from .views import LoginView, RegisterView, profile, accept_friend_request, send_friend_request

app_name = 'profiles'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<user_id>', profile, name='profile'),
    path('send_friend_request/<user_id>', send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<request_id>', accept_friend_request, name='accept_friend_request'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    friends = models.ManyToManyField("User", blank=True)

class FriendRequest(models.Model):
    sender = models.ForeignKey(User, related_name='sender', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='receiver', on_delete=models.CASCADE)

threads/models.py
from django.db import models
from django.utils import timezone

from profiles.models import User

class Thread(models.Model):
    title = models.CharField(max_length=256)
    text = models.CharField(max_length=512)
    pub_date = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title

class Comment(models.Model):
    text = models.CharField(max_length=256)
    pub_date = models.DateTimeField(default=timezone.now)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.text

class Upvote(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    vote_date = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.user.username + ' upvoted "' + self.thread.title + '"'

profiles/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=128, 
                                required=True,
                                widget=forms.TextInput(attrs={
                                    'placeholder': 'Username',
                                    'class': 'form-control'
                                }),
                                label="")
    password = forms.CharField(max_length=64, 
                                required=True,
                                widget=forms.PasswordInput(attrs={
                                    'placeholder': 'Password',
                                    'class': 'form-control',
                                    'data-toggle': 'password',
                                    'id': 'password',
                                    'name': 'password'
                                }),
                                label="")
    remember_me = forms.BooleanField(required=False, 
                                        label="",
                                        widget=forms.CheckboxInput(attrs={
                                            'class': 'form-check-input',
                                            'id': 'remember-me'
                                        }),
                                        help_text="<label class=\"form-check-label\" for=\"remember-me\">Remember me</label>")

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']

class RegistrationForm(UserCreationForm):
    username = forms.CharField(max_length=128, 
                                required=True,
                                widget=forms.TextInput(attrs={
                                    'placeholder': 'Username',
                                    'class': 'form-control'
                                }),
                                label="")
    password1 = forms.CharField(max_length=64, 
                                required=True,
                                widget=forms.PasswordInput(attrs={
                                    'placeholder': 'Password',
                                    'class': 'form-control',
                                    'data-toggle': 'password',
                                    'id': 'password2',
                                    'name': 'password2'
                                }),
                                label="")
    password2 = forms.CharField(max_length=64, 
                                required=True,
                                widget=forms.PasswordInput(attrs={
                                    'placeholder': 'Confirm Password',
                                    'class': 'form-control',
                                    'data-toggle': 'password',
                                    'id': 'password2',
                                    'name': 'password2'
                                }),
                                label="")
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

profiles/views.py
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.decorators import login_required
from django.dispatch import receiver
from django.http import HttpResponseRedirect

from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic

from profiles.models import FriendRequest

from .forms import LoginForm, RegistrationForm
from .models import User

class LoginView(BaseLoginView):
    form_class = LoginForm
    redirect_authenticated_user = True
    template_name = 'profiles/login.html'

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            self.request.session.set_expiry(0)
            self.request.session.modified = True
        
        return super(LoginView, self).form_valid(form)

class RegisterView(generic.CreateView):
    form_class = RegistrationForm
    success_url = reverse_lazy('login')
    template_name = 'profiles/register.html'

def profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    friend_requests = None
    friends = user.friends.all()
    is_friend = False
    if user == request.user:
        friend_requests = FriendRequest.objects.filter(receiver=user)
    else:
        is_friend = request.user in friends
    return render(request, 'profiles/profile.html', { 'target_profile': user, 'friend_requests': friend_requests, 'is_friend': is_friend, 'friends': friends })

@login_required
def send_friend_request(request, user_id):
    receiver = get_object_or_404(User, id=user_id)
    friend_request, created = FriendRequest.objects.get_or_create(sender=request.user, receiver=receiver)
    if created:
        return HttpResponseRedirect(reverse('profiles:profile', args=(receiver.id, )))
    else:
        return HttpResponseRedirect(reverse('profiles:profile', args=(request.user.id, )))

@login_required
def accept_friend_request(request, request_id):
    friend_request = FriendRequest.objects.get(id=request_id)
    if friend_request.receiver == request.user:
        friend_request.receiver.friends.add(friend_request.sender)
        friend_request.sender.friends.add(friend_request.receiver)
        friend_request.delete()
    return HttpResponseRedirect(reverse('profiles:profile', args=(friend_request.sender.id, )))

templates/profiles/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends App - Authentication</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand text-center" href="/">Friends Network</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                      <a href="{% url 'logout' %}" class="nav-link">Log out</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>

</html>

templates/profiles/login.html
{% extends 'profiles/base.html' %}

{% block content %}
<div class="container my-3">
    <h2>Log in</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-sm" type="submit">Log in</button>
        <a class="text-decoration-none" href="{% url 'profiles:register' %}">Don't have an account?</a>
    </form>
</div>
{% endblock %}

templates/profiles/profile.html
{% extends 'profiles/base.html' %}

{% block content %}
<div class="container my-3">
    <div class="text-center">
        <h2>{{ target_profile.username }}'s profile</h2>
        <span class="d-block">Registered since {{ target_profile.date_joined }}</span>
        <span class="d-block">{{ target_profile.upvote_set.count }} upboat{{ target_profile.upvote_set.count|pluralize }} given</span>
        <span class="d-block">{{ target_profile.comment_set.count }} comment{{ target_profile.comment_set.count|pluralize }} made</span>
        <span class="d-block">{{ target_profile.thread_set.count }} thread{{ target_profile.thread_set.count|pluralize }} written</span>
    </div>

    <div class="mb-5">
        <h3>Friend{{ friends.count|pluralize }}</h3>
        {% for friend in friends %}
            <a class="d-block text-decoration-none" href="{% url 'profiles:profile' friend.id %}">{{ friend.username }}</a>
        {% endfor %}
    </div>

    {% if target_profile != user %}
        {% if is_friend %}
            <p>You and {{ target_profile.username }} are friends.</p>
        {% else %}
            {% if user.is_authenticated %}
                <a class="d-block text-decoration-none" href="{% url 'profiles:send_friend_request' target_profile.id %}">Send friend request</a>
            {% else %}
                <a class="d-block text-decoration-none" href="{% url 'profiles:login' %}">Login or sign up to send a friend request</a>
            {% endif %}
        {% endif %}
    {% else %}
        <h3>Friend Requests</h3>
        {% if friend_requests|length > 0 %}
            {% for friend_request in friend_requests %}
                <span class="d-block"><a class="text-decoration-none" href="{% url 'profiles:profile' friend_request.sender.id %}">{{ friend_request.sender.username }}</a> wants to be your friend <a href="{% url 'profiles:accept_friend_request' friend_request.id %}">Accept</a></span>
            {% endfor %}
        {% else %}
            <p>None at the moment.</p>
        {% endif %}
    {% endif %}
</div>
{% endblock %}

templates/profiles/register.html
{% extends 'profiles/base.html' %}

{% block content %}
<div class="container my-3">
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary btn-sm" type="submit" value="Sign up">
        <a class="text-decoration-none" href="{% url 'profiles:login' %}">Already have an account?</a>
    </form>
</div>
{% endblock %}